export const nodeData = [
  { id: 1, name: '约翰内斯堡', domain: 'objectstorage.af-johannesburg-1.oraclecloud.com' },
  // { id: 2, name: '春川', domain: 'objectstorage.ap-chuncheon-1.oraclecloud.com' },
  // { id: 3, name: '海得拉巴', domain: 'objectstorage.ap-hyderabad-1.oraclecloud.com' },
  // { id: 4, name: '墨尔本', domain: 'objectstorage.ap-melbourne-1.oraclecloud.com' },
  // { id: 5, name: '孟买', domain: 'objectstorage.ap-mumbai-1.oraclecloud.com' },
  // { id: 6, name: '大阪', domain: 'objectstorage.ap-osaka-1.oraclecloud.com' },
  // { id: 7, name: '首尔', domain: 'objectstorage.ap-seoul-1.oraclecloud.com' },
  // { id: 8, name: '新加坡', domain: 'objectstorage.ap-singapore-1.oraclecloud.com' },
  // { id: 9, name: '悉尼', domain: 'objectstorage.ap-sydney-1.oraclecloud.com' },
  // { id: 10, name: '东京', domain: 'objectstorage.ap-tokyo-1.oraclecloud.com' },
  // { id: 11, name: '蒙特利尔', domain: 'objectstorage.ca-montreal-1.oraclecloud.com' },
  // { id: 12, name: '多伦多', domain: 'objectstorage.ca-toronto-1.oraclecloud.com' },
  // { id: 13, name: '阿姆斯特丹', domain: 'objectstorage.eu-amsterdam-1.oraclecloud.com' },
  // { id: 14, name: '法兰克福', domain: 'objectstorage.eu-frankfurt-1.oraclecloud.com' },
  // { id: 15, name: '马德里', domain: 'objectstorage.eu-madrid-1.oraclecloud.com' },
  // { id: 16, name: '马赛', domain: 'objectstorage.eu-marseille-1.oraclecloud.com' },
  // { id: 17, name: '米兰', domain: 'objectstorage.eu-milan-1.oraclecloud.com' },
  // { id: 18, name: '巴黎', domain: 'objectstorage.eu-paris-1.oraclecloud.com' },
  // { id: 19, name: '斯德哥尔摩', domain: 'objectstorage.eu-stockholm-1.oraclecloud.com' },
  // { id: 20, name: '苏黎世', domain: 'objectstorage.eu-zurich-1.oraclecloud.com' },
  // { id: 21, name: '耶路撒冷', domain: 'objectstorage.il-jerusalem-1.oraclecloud.com' },
  // { id: 22, name: '阿布扎比', domain: 'objectstorage.me-abudhabi-1.oraclecloud.com' },
  // { id: 23, name: '迪拜', domain: 'objectstorage.me-dubai-1.oraclecloud.com' },
  // { id: 24, name: '吉达', domain: 'objectstorage.me-jeddah-1.oraclecloud.com' },
  // { id: 25, name: '墨西哥城', domain: 'objectstorage.mx-monterrey-1.oraclecloud.com' },
  // { id: 26, name: '克雷塔罗', domain: 'objectstorage.mx-queretaro-1.oraclecloud.com' },
  // { id: 27, name: '波哥大', domain: 'objectstorage.sa-bogota-1.oraclecloud.com' },
  // { id: 28, name: '圣地亚哥', domain: 'objectstorage.sa-santiago-1.oraclecloud.com' },
  // { id: 29, name: '圣保罗', domain: 'objectstorage.sa-saopaulo-1.oraclecloud.com' },
  // { id: 30, name: '瓦尔帕莱索', domain: 'objectstorage.sa-valparaiso-1.oraclecloud.com' },
  // { id: 31, name: '维尼都', domain: 'objectstorage.sa-vinhedo-1.oraclecloud.com' },
  // { id: 32, name: '卡迪夫', domain: 'objectstorage.uk-cardiff-1.oraclecloud.com' },
  // { id: 33, name: '伦敦', domain: 'objectstorage.uk-london-1.oraclecloud.com' },
  // { id: 34, name: '阿什本', domain: 'objectstorage.us-ashburn-1.oraclecloud.com' },
  // { id: 35, name: '芝加哥', domain: 'objectstorage.us-chicago-1.oraclecloud.com' },
  // { id: 36, name: '凤凰城', domain: 'objectstorage.us-phoenix-1.oraclecloud.com' },
  // { id: 37, name: '圣荷西', domain: 'objectstorage.us-sanjose-1.oraclecloud.com' },
  // ... 添加所有其他节点
];
